export function generateLogoIcon(size, cornerRadius) {
  const canvas = document.createElement('canvas');
  const s = size * 2;
  canvas.width = s;
  canvas.height = s;
  const ctx = canvas.getContext('2d');
  const gradient = ctx.createLinearGradient(0, 0, s, s);
  gradient.addColorStop(0, '#1B3A32');
  gradient.addColorStop(1, '#2d6b5a');
  ctx.fillStyle = gradient;
  const r = cornerRadius * 2;
  ctx.beginPath();
  ctx.moveTo(r, 0);
  ctx.lineTo(s - r, 0);
  ctx.quadraticCurveTo(s, 0, s, r);
  ctx.lineTo(s, s - r);
  ctx.quadraticCurveTo(s, s, s - r, s);
  ctx.lineTo(r, s);
  ctx.quadraticCurveTo(0, s, 0, s - r);
  ctx.lineTo(0, r);
  ctx.quadraticCurveTo(0, 0, r, 0);
  ctx.closePath();
  ctx.fill();
  ctx.fillStyle = '#ffffff';
  ctx.font = `${Math.round(s * 0.5)}px sans-serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText('A', s / 2, s / 2 + s * 0.015);
  return canvas.toDataURL('image/png');
}
